version: "3.5"
services:
  testcrowd-mssqldb:
    image: mcr.microsoft.com/mssql/server:2017-latest
    container_name: testcrowd-mssqldb
    hostname: testcrowd-mssqldb
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Test@123456
    ports:
      - "1433:1433"
    volumes:
      - "./sql-backup:/var/opt/mssql/data"
    networks:
      - default
  testcrowd-app:
    build:
      context: ./
    image: testcrowd-docker
    container_name: testcrowd-app
    hostname: testcrowd-app
    restart: on-failure
    ports:
      - "8080:8080"
    depends_on:
      - testcrowd-mssqldb
    networks:
      - default
networks:
  default:
    name: testcrowd-network