## Spring
spring:

  # Docker
  datasource:
    url: 'jdbc:sqlserver://testcrowd-mssqldb:1433'
    username: 'sa'
    password: 'Test@123456'
    driverClassName: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'

  # Hibernate properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update    # options: (create, create-drop, validate, update)
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.SQLServer2012Dialect'

  # Internationalization
  messages:
    basename: messages/messages

  # Cache
  resources:
    cache:
      cachecontrol:
        max-age: 12h    # maximum time static resources should be cached

  # Web
  thymeleaf:
    mode: HTML

## Logging
logging:
  level:
    org:
      springframework: INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

## Actuator / Management
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
