## Spring
spring:

  # Docker
  datasource:
    url: 'jdbc:sqlserver://testcrowd-mssqldb:1433'
    username: 'sa'
    password: 'Test@123456'
    driverClassName: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'

  # Hibernate properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update    # options: (create, create-drop, validate, update)
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.SQLServer2012Dialect'

  # Security / OAuth2
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 563033980736-lrjr9jcduv1mu76sf5cs8j8l41bhocfv.apps.googleusercontent.com
            client-secret: Gta9S6LqagyufErt_zTmVvxC
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
          facebook:
            client-id: 835850046853866
            client-secret: f588bb67a72782a483a94115bd5fb70f
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - public_profile
          github:
            client-id: e85b058350a3596463e6
            client-secret: b5f974d6e28bb72fad28d64914a28413cbd7f6eb
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - user:email
              - read:user

  # Internationalization
  messages:
    basename: messages/messages

  # Resources / Cache
  resources:
    cache:
      cachecontrol:
        max-age: 12h    # maximum time static resources should be cached

  # Web
  thymeleaf:
    mode: HTML

## Logging
logging:
  level:
    org:
      springframework: INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

## Actuator / Management
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
