## Spring
spring:

  # Docker
  datasource:
    url: 'jdbc:sqlserver://testcrowd-mssqldb:1433'
    username: 'sa'
    password: 'Test@123456'
    driverClassName: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'

  # Hibernate properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update    # options: (create, create-drop, validate, update)
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.SQLServer2012Dialect'

  # Security / OAuth2
  # security:
    # oauth2:
      # client:
        # registration:
          # google:
            # clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
            # clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
            # redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            # scope:
              # - email
              # - profile
          # facebook:
            # clientId: 121189305185277
            # clientSecret: 42ffe5aa7379e8326387e0fe16f34132
            # redirectUri: "{baseUrl}/oauth2/callback/{registrationId}" # Note that facebook now mandates the use of https redirect URIs, so make sure your app supports https in production
            # scope:
              # - email
              # - public_profile
        # provider:
          # facebook:
            # authorizationUri: https://www.facebook.com/v3.0/dialog/oauth
            # tokenUri: https://graph.facebook.com/v3.0/oauth/access_token
            # userInfoUri: https://graph.facebook.com/v3.0/me?fields=id,first_name,middle_name,last_name,name,email,verified,is_verified,picture.width(250).height(250)

  # Internationalization
  messages:
    basename: messages/messages

  # Resources / Cache
  resources:
    cache:
      cachecontrol:
        max-age: 12h    # maximum time static resources should be cached

  # Web
  thymeleaf:
    mode: HTML

## App / OAuth2
# app:
  # auth:
    # tokenSecret: 926D96C90030DD58429D2751AC1BDBBC
    # tokenExpirationMsec: 864000000
  # oauth2:
    # authorizedRedirectUris:
      # - http://localhost:8080/oauth2/redirect

## Logging
logging:
  level:
    org:
      springframework: INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE

## Actuator / Management
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'
