## Spring
spring:

  # MSSQL
  datasource:
    url: 'jdbc:sqlserver://testcrowd-mssqldb:1433'
    # url: 'jdbc:sqlserver://localhost:1433'
    username: 'sa'
    password: 'Test@123456'
    driverClassName: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'

  # Hibernate properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update    # options: (create, create-drop, validate, update)
      # ddl-auto: create-drop
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.SQLServer2012Dialect'

  # Internationalization
  messages:
    basename: messages/messages

  # Resources / Cache
  resources:
    cache:
      cachecontrol:
        max-age: 12h    # maximum time static resources should be cached

  # Web
  thymeleaf:
    mode: HTML


## Logging
logging:
  level:
    org:
      springframework: INFO
# logging.level.org.springframework.web=DEBUG
# logging.level.org.springframework.context.annotation=TRACE


## Actuator / Management
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'


## Server
server:
  error:
    include-stacktrace: always
    include-exception: true
    whitelabel:
      enabled: false

## PayPal
payPal:
  mode: 'sandbox'
  client:
    id: 'AfszrU41imldmUDZJp_5zyJDiD9N61N_GRlpJSzftPbiA0zIoOH2r7UzXe0re7TBudZl3ngQktCOOfnU'
    secret: 'EMvVxXesBEcz1bIsJT8mjVR_M8NNRJXXNfP04fm8AyyU3V7VSqqNwNsZyCKU9_j6PacrOTtZjQRUCl4r'


## MULTIPART (MultipartProperties)
servlet:
  multipart:
    # Enable multipart uploads
    enabled: true

    # Threshold after which files are written to disk.
    file-size-threshold: 2KB

    # Max file size.
    max-file-size: 200MB

    # Max Request Size
    max-request-size: 215MB