## Spring
spring:

  # MSSQL
  datasource:
    url: 'jdbc:sqlserver://testcrowd-mssqldb:1433'
    # url: 'jdbc:sqlserver://localhost:1433'
    username: 'sa'
    password: 'Test@123456'
    driverClassName: 'com.microsoft.sqlserver.jdbc.SQLServerDriver'

  # Hibernate properties
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
      # ddl-auto: create-drop
    properties:
      hibernate:
        dialect: 'org.hibernate.dialect.SQLServer2012Dialect'

  # Internationalization
  messages:
    basename: messages/messages

  # Resources / Cache
  resources:
    cache:
      cachecontrol:
        max-age: 12h    # maximum time static resources should be cached

  # Web
  thymeleaf:
    mode: HTML

  # MULTIPART (MultipartProperties)
  servlet:
    multipart:
      enabled: true               # enable multipart uploads
      file-size-threshold: 200MB    # threshold after which files are written to disk
      max-file-size: 400MB        # max file size
      max-request-size: 415MB     # max request size


## Logging
logging:
  level:
    org:
      springframework: INFO


## Actuator / Management
management:
  endpoints:
    web:
      base-path: /manage
      exposure:
        include: '*'


## Server
server:
  error:
    include-stacktrace: always
    include-exception: true
    whitelabel:
      enabled: false


## PayPal
payPal:
  mode: 'sandbox'
  client:
    id: 'AfszrU41imldmUDZJp_5zyJDiD9N61N_GRlpJSzftPbiA0zIoOH2r7UzXe0re7TBudZl3ngQktCOOfnU'
    secret: 'EMvVxXesBEcz1bIsJT8mjVR_M8NNRJXXNfP04fm8AyyU3V7VSqqNwNsZyCKU9_j6PacrOTtZjQRUCl4r'
